### PR TITLE
build ngx kafka module as dynamic module

### PR DESCRIPTION
**Pull request by yourpleasure**
I change the config file and now the module can be compiled as both static and dynamic module.

### CODE REVIEW

**Comment by salekseev** [comment]
+1

**Comment by brg-liuwei** [comment]
```
If you compile module as a dynamic module, you must add
   
    load_module /path/to/ngx_http_kafka_module.so;

before "http" directive besides adding the code to nginx config file. After that you can use the module by just executing `nginx -c /path/to/nginx.conf -s reload`.
```

The position of directive load_module maybe have some mistakes. I tried the conf as follows with `nginx -t` and the error occurs: `nginx: [emerg] "load_module" directive is specified too late in /opt/mynginx/conf/nginx.conf`

```
events {
    worker_connections  1024;
}

load_module /opt/mynginx/modules/ngx_http_kafka_module.so;

http {
    include       mime.types;
    default_type  application/octet-stream;
```

Can you describe more precise for the position of directive `load_module` in README.md?

**Comment by yourpleasure** [comment]
Sorry. This is a mistake. We can put
```
load_module /path/to/ngx_http_kafka_module.so;
```
at the very beginning of the nginx config file. In my test environment, I put it before 'event' directive and it works. I think it may work when I put it just before 'http' directive, but it fails. I have changed the README file.

**Comment by yourpleasure** [comment]
Sorry again. I don't observe that your repo has been updated. I will merge it and do some test.

**Comment by brg-liuwei** [comment]
@yourpleasure Hi, my friend, thank you very much for this PR. I tested the PR and it is worked in my environment. I'm very glad to accept this PR.

And there is an another request to you. To ensure the high quality of this module, I enabled [travis-ci](https://travis-ci.org/) for auto continuous integration testing. We can edit file `.travis.yml` to add some scripts for auto-testing. And, do you mind contributing another PR that add some scripts in `.travis.yml` and add some test cases in directory `t/` for auto-testing the directive of `load_module /path/to/ngx_http_kafka_module.so;`

**Comment by yourpleasure** [comment]
@brg-liuwei OK. I will study travis-ci and do some test.

**Comment by brg-liuwei** [comment]
@yourpleasure Travis-ci is easy to study and is very interesting. For addition, I strongly recommend you to learn about [Test::Nginx](https://openresty.gitbooks.io/programming-openresty/content/testing/test-nginx.html). You can use it to create many test case very easily. Wish you can like those tools, and if this is any problems, feel free to send mail to me :).

**Pull request merged**
